name: Rebuild containers
on:
  workflow_dispatch:

jobs:
  server:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        libc: [glibc, musl]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and push
      uses: docker/build-push-action@v3
      with:
        tags: ghcr.io/${{ github.repository }}-${{ matrix.libc }}:latest
        context: arch/${{ matrix.libc }}
        platforms: linux/amd64,linux/arm64
        push: true

  pi:
    runs-on: [self-hosted, linux, ARM]

    steps:
    - name: Checkout
      uses: actions/checkout@v2

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.repository_owner }}
        password: ${{ secrets.CR_PAT }}

    - name: Build and Push Docker Image
      run: |
        cd ${{ env.context }}
        docker build . -t ${{ env.tag }}
        docker push ${{ env.tag }}
      env:
        context: arch/arm
        tag: ghcr.io/${{ github.repository }}-arm:latest
