name: Run tests
on:
  workflow_dispatch:
  push:
  pull_request:
    branches:
      - main

jobs:
  run-tests:
    name: Rebuild & Test
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
          - windows-latest
          - ubuntu-18.04
        node:
          - 10
          - 15

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}

    - name: Use Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable

    - name: Build for Metal
      if: ${{ matrix.os == 'macos-latest' }}
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features metal,window

    - name: Build for Vulkan
      if: ${{ matrix.os != 'macos-latest' }}
      run: |
        npm ci --ignore-scripts
        npm run build -- --release --features vulkan,window

    - name: Run tests
      run: npm test
